# Generated by Django 5.1.7 on 2025-04-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=150)),
                ("message", models.TextField()),
                ("image", models.ImageField(upload_to="testimonials/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
