# Generated by Django 5.2.2 on 2025-06-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karunya_app', '0005_remove_testimonial_name_testimonial_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='rating',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
